title: Geronimo Dubra
logo: /assets/img/profile_pic.png
#descriptioon: text belox the image
show_downloads: false
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
